### ISSUE TITLE
Wrong category when querying the API

### ISSUE THREAD

**Issue by cimentadaj** [femueller/python-n26#107] opened 2021-08-09 13:49 UTC
I'm not sure this is due to the the `python-n26` library (which by the way is awesome and I use frequently, thanks!) but I keep getting wrong categories when querying the API with respect to the data in the N26 App. 

I just had an expense classified as Food-Groceries and I manually changed it to Education in the App. I close the N26 App and come back to it to see that it respected the change. However, when I make a request through the API I still see the Food-Groceries category. This is not a thing due to the lag of the data since I've repeated this experiment with more than a week apart and I keep getting old categories.

Anyone experiencing this?

**Comment by femueller** [comment] 2021-08-09 15:07
Hey @cimentadaj, happy to hear that you find it useful!

I've just tested it myself and I can confirm that this data is not being immediately updated.
Looks like n26 doesn't update it on their "public" API endpoint.

May I ask what you're planning to use this feature for? I was also thinking about the tagging feature, but it also looks like this is not being exposed to the API.

**Comment by cimentadaj** [comment] 2021-08-09 15:23
Weirdly, this worked for the past year or so up until 2-3 weeks ago. Do you think this is a bug or this is on purpose?

I have a personal finance app where I classify expenses based on a custom category that I have. In the N26 App I recode some expenses based on my personal custom category and then my personal finance app just groups them to see where I'm spending stuff. Just what any other finance app would do but I have some custom stuff that I like. Do you know if they expose any of the tags in the public API?

**Comment by markusressel** [comment] 2021-08-09 17:21
Its certainly not a bug in python-n26, since it hasn't changed in any meaningful way (at least not that I know of).
Whether N26 is changing their backend and accidentally breaking the public API in the process is unknown to us as it is to anyone not working within the company. Not sure if we can do anything about this except complain to N26.

**Comment by femueller** [comment] 2021-08-10 14:09
> Not sure if we can do anything about this except complain to N26.

I'll try to exactly that and will ask the developers I've been texting with before. Maybe they have any clue.
But I don't know how our chances are to get this fixed in a timely manner.

**Comment by femueller** [comment] 2021-08-11 14:39
Both contacts I've had are no longer working @n26. Trying to find another contact. :)

**Comment by julian-klode** [comment] 2021-12-10 17:01
In a similar manner, now VisibleTS == CreatedTS, so you can't see the real date when you actually purchased something anymore.

**Comment by femueller** [comment] 2022-01-10 12:25
It's almost impossible to reach somebody at N26 and there is not really an interest for this project within the company. I am closing this issue now, because it's not something we can fix at the moment.

**Closed by femueller** 2022-01-10 12:25 UTC
