### ISSUE TITLE
problem with auth

### ISSUE THREAD

**Issue by mschultheiss83** [femueller/python-n26#129] opened 2023-05-17 07:35 UTC
`BASE_URL_GLOBAL = 'https://api.tech26.global'` is not working for me

i replaced it with `BASE_URL_GLOBAL = 'https://api.tech26.de'`

**Comment by mschultheiss83** [comment] 2023-05-17 07:36
see https://github.com/femueller/python-n26/pull/127 for details

**Comment by markusressel** [comment] 2023-05-17 17:45
Hey @mschultheiss83, please try version 3.3.1 .

**Comment by markusressel** [comment] 2023-05-17 17:49
Closing as duplicate of #125

**Closed by markusressel** 2023-05-17 17:49 UTC
Labels: bug
